//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamManage_VoteEntities : DbContext
    {
        public TeamManage_VoteEntities()
            : base("name=TeamManage_VoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VoteDetail> VoteDetails { get; set; }
        public virtual DbSet<VoteItem> VoteItems { get; set; }
        public virtual DbSet<VoteProject> VoteProjects { get; set; }
    }
}
